development:
  forest_env_secret: 0cbe00dc379dd97c651d1fedcf2647ad9d3422962c47d9d8ae4c30c07b5143be
  forest_auth_secret: QsqlIWmNzNSHUMGR7u0T8A
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
